import { Inter } from 'next/font/google'
import { ThemeProvider } from '@/provider/theme-provider'
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar'
import AppSidebar from '@/components/sidebar/'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'AI聊天、翻译、图片生成',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<ThemeProvider>
					<SidebarProvider>
						<AppSidebar />
						<main>
							<SidebarTrigger />
							{children}
						</main>
					</SidebarProvider>
				</ThemeProvider>
			</body>
		</html>
	)
}
